### ISSUE TITLE
Callback failure from aTV hub for a scene

### ISSUE THREAD

**Issue by paulbadcock** [jfdoube/homebridge-sinope#1]
When I try to change the temperature using an AppleTV hub **in a scene** I get the following error. The temperature setting directly on an accessory works correctly.

info: Outgoing PUT https://neviweb.com/api/device/DEVICEID/setpoint
/usr/lib/node_modules/homebridge-sinope/src/kit/characteristics/temperature.characteristic.js:125
callback(undefined, 1);
^

TypeError: callback is not a function
at Object.setTargetHeatingCoolingState [as set] (/usr/lib/node_modules/homebridge-sinope/src/kit/characteristics/temperature.characteristic.js:125:3)
at characteristic.on (/usr/lib/node_modules/homebridge-sinope/src/kit/characteristics/temperature.characteristic.js:45:20)
at emitMany (events.js:127:13)
at emit (events.js:201:7)
at Characteristic.setValue (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:155:10)
at Bridge.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:727:22)
at Array.forEach (native)
at Bridge.Accessory._handleSetCharacteristics (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:672:8)
at emitMany (events.js:127:13)
at HAPServer.emit (events.js:201:7)
at HAPServer._handleCharacteristics (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:966:10)
at HAPServer.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:203:39)
at emitNone (events.js:86:13)
at IncomingMessage.emit (events.js:185:7)
at endReadableNT (_stream_readable.js:974:12)
at _combinedTickCallback (internal/process/next_tick.js:74:11)

**Comment by jfdoube** [comment]
I'll look into it

**Comment by paulbadcock** [comment]
Thanks, if you need anything let me know!
